language:
  - scala
before_install:
  - test $TRAVIS_PULL_REQUEST == "false" && ./deploy.prep
  - test $TRAVIS_PULL_REQUEST == "false" && eval `ssh-agent`
  - test $TRAVIS_PULL_REQUEST == "false" && ssh-add deploy
before_script:
  - sudo pip install sphinx
  - sudo pip install sphinx_rtd_theme
script:
  - sbt ++$TRAVIS_SCALA_VERSION test makeSite
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt publish ghpagesPushSite
scala:
  - 2.11.4
jdk:
  - oraclejdk8
