language:
  - scala
before_install:
  - git config --global user.name "Travis build"
  - git config --global user.email "krasserm@googlemail.com"
  - openssl aes-256-cbc -K $encrypted_f0f220afbce8_key -iv $encrypted_f0f220afbce8_iv -in deploy.enc -out deploy -d
  - chmod 600 deploy
  - eval `ssh-agent`
  - ssh-add deploy
before_script:
  - sudo pip install sphinx
  - sudo pip install sphinx_rtd_theme
script:
  - sbt ++$TRAVIS_SCALA_VERSION test makeSite
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt publish ghpagesPushSite
scala:
  - 2.11.4
jdk:
  - oraclejdk8
